Exercice1

In [1]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Exercice2

In [2]:
import numpy as np
liste = [3.14, 2.17, 0, 1, 2]
tableau = np.array(liste).astype(int)
print(tableau)

[3 2 0 1 2]


Exercice3

In [3]:
import numpy as np
tableau = np.arange(1, 10).reshape(3, 3)
print(tableau)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice4

In [4]:
import numpy as np
tableau = np.random.rand(4, 5)
print(tableau)

[[0.51685377 0.50709721 0.71046608 0.51482433 0.65911715]
 [0.80976296 0.76054274 0.1542697  0.40935144 0.63431815]
 [0.03544118 0.63100068 0.69532725 0.1895832  0.6116272 ]
 [0.96918236 0.13653269 0.04355296 0.54579055 0.51980042]]


Exercice5

In [5]:
import numpy as np
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])
deuxieme_ligne = array[1]
print(deuxieme_ligne)

[20 21 22 23 24]


Exercice6

In [6]:
import numpy as np
array = np.arange(10)
array_inverse = array[::-1]
print(array_inverse)

[9 8 7 6 5 4 3 2 1 0]


Exercice7

In [7]:
import numpy as np
matrice_identite = np.eye(4)
print(matrice_identite)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice8

In [8]:
import numpy as np
array = np.arange(10)
somme = np.sum(array)
moyenne = np.mean(array)
print(f"Sum: {somme}, Average: {moyenne}")

Sum: 45, Average: 4.5


Exercice9

In [9]:
import numpy as np
array = np.arange(1, 21)
matrice = array.reshape(4, 5)
print(matrice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice10

In [10]:
import numpy as np
array = np.arange(10)
impairs = array[array % 2 != 0]
print(impairs)

[1 3 5 7 9]
